language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install coveralls
- pip install -r requirements-dev.txt
script:
- py.test --cov=getalltweets tests/ && pylint getalltweets/

after_success: coveralls
