language: python
python:
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
install:
- pip install coveralls
- pip install -r requirements-dev.txt
script:
- py.test --cov=postrun tests/
# after_success: coveralls
