language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install coveralls
- pip install -r requirements-dev.txt
script:
- py.test --cov=getalltweets tests/ && pylint getalltweets/

# after_success: coveralls
